package com.dp.assign3;

/*
Student Name: Daniel Perusse
Student ID: 200551990
Student Email: 200551990@student.georgianc.on.ca
COMP3026 - Application Security Programming
*/

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Servlet implementation class RegisterServlet
 */
@WebServlet("/RegisterServlet")
public class RegisterServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private RegisterDao rtDao;
	private Md5HashingClass md5;

	public void init() {
		rtDao = new RegisterDao();
		md5 = new Md5HashingClass();
	}

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public RegisterServlet() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		// doGet(request, response);
		String userName = request.getParameter("userName");

		// immediately hash the password
		String password = md5.getMd5(request.getParameter("password"));
		System.out.println("Your HashCode Generated by MD5 is: " + password);
		
		String phoneNumber = request.getParameter("phoneNumber");
		String email = request.getParameter("email");

		RegisterPage rp = new RegisterPage();
		rp.setUser_name(userName);
		rp.setPassword(password);
		rp.setPhone_number(phoneNumber);
		rp.setEmail(email);

		try {
			rtDao.registerPage(rp);
		} catch (Exception e) {
			System.out.println(e);
		}
	}

}
